---

services:

  nginx_a:
    image: gretel/nginx_yesgretel
    depends_on: [nginx_b]
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx_a.conf:/etc/nginx/nginx.conf
      - ./nginx_a.logs:/var/log/nginx/

    environment:
      GRETEL_PID: 1048577 # =0x100001
    restart: always

  nginx_b:
    image: gretel/nginx_yesgretel
    build:
      context: ../nginx-gretel
      args:
        GRETEL_ENABLE: 1
    ports:
      - "127.0.0.1:81:81"
    volumes:
      - ./nginx_b.conf:/etc/nginx/nginx.conf
      - ./nginx_b.logs:/var/log/nginx/
    environment:
      GRETEL_PID: 1048578 # =0x100002
    restart: always
