---

services:

  nginx1:
    image: gretel/nginx-nogretel
    depends_on: [nginx2]
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/nginx.conf
      - ./nginx1.logs:/var/log/nginx/
    restart: always

  nginx2:
    image: gretel/nginx-nogretel
    build:
      context: ../nginx-gretel
      args:
        GRETEL_ENABLE: 0  #
    ports:
      - "127.0.0.1:81:81"
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
      - ./nginx2.logs:/var/log/nginx/
    restart: always
