---

services:

  nginx_a:
    image: gretel/nginx-nogretel
    depends_on: [nginx_b]
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx_a.conf:/etc/nginx/nginx.conf
      - ./nginx_a.logs:/var/log/nginx/
    restart: always

  nginx_b:
    image: gretel/nginx-nogretel
    build:
      context: ../nginx-gretel
      args:
        GRETEL_ENABLE: 0  #
    ports:
      - "127.0.0.1:81:81"
    volumes:
      - ./nginx_b.conf:/etc/nginx/nginx.conf
      - ./nginx_b.logs:/var/log/nginx/
    restart: always
